### ISSUE TITLE
Export-VmsClientProfile fails on method named GetPropertyKeys

### ISSUE THREAD

**Issue by davidfrankks** [MilestoneSystemsInc/PowerShellSamples#88] opened 2023-05-04 13:08 UTC
https://www.milestonepstools.com/functions/export-vmsclientprofile/#description

Get-VmsClientProfile | Export-VmsClientProfile -Path .\clientprofiles.json

Method invocation failed because [System.Collections.Generic.List`1[[VideoOS.Platform.ConfigurationItems.ClientProfileGisMapChildItem, VideoOS.Platform, 
Version=1.0.0.0, Culture=neutral, PublicKeyToken=bc60fba4a7969f89]]] does not contain a method named 'GetPropertyKeys'.

MS 2022 R3 - MiletonePSTools latest pull.

**Comment by joshooaj** [comment] 2023-05-05 23:25
Thanks @davidfrankks,

I think the issue is you may not be using a product version with support for "smart maps"?

I can reproduce the error if I create an empty list of type `VideoOS.Platform.ConfigurationItems.ClientProfileGisMapChildItem` and call "GetPropertyKeys()" on the empty list.

This will be fixed in the next version by skipping any client profile "namespaces" with no attributes.

**Comment by joshooaj** [comment] 2023-08-18 05:40
Hi @davidfrankks,

This should be resolved in the 23.2.1 version of MilestonePSTools now available on psgallery. Feel free to re-open or open a new issue if you still have issues!

**Closed by joshooaj** 2023-08-18 05:40 UTC
Labels: bug
