### ISSUE TITLE
Changed settings are not applied until the recording server is restarted

### ISSUE THREAD

**Issue by thejurassic** [MilestoneSystemsInc/PowerShellSamples#52] opened 2022-05-13 11:09 UTC
Ive been trying out this powershell module, but ive noticed that if I change a setting (eg set a microphone to enable recording) that the setting DOES get changed immediately in the management console but it DOES NOT take affect until the recording server service is restarted. Ive actually tried making the same change in the management console and the change also does NOT take affect until the recording server is restarted. So I can only assume this is a limitation within Milestone that changed settings dont actually get applied until the recording server is restarted. Does that sound right? 
If so, can we add a command tell the recording server to re-read and apply its config? Or failing that, a command to restart a recording server? 
Note: Ive also tried invoking the Save method on the recording server object but that has no effect. Only restarting the service ensures the settings are applied.

**Comment by joshooaj** [comment] 2022-05-13 13:57
Hi Matt,

Thanks for trying it out and sharing this experience here! If you have to restart the recording server service for changes to take effect, something is very, very wrong :)

I haven't experienced this myself and will try it out later today. Can you share the commands you used, the Milestone VMS version, and the camera model and driver used in Milestone?

Do you experience the same issue when changing the setting directly in Management Client?

/Josh

**Comment by rdo-mgowland** [comment] 2022-05-13 15:46
Can you test the following in your environment:
Have a camera with an attached microphone where the camera is set to record but the microphone is set to not record..... Then view the recorded footage to ensure the audio is not recording but the camera footage is recording....
Then set the microphone to record. The change should ideally be pretty well instant, and in your recorded footage for that camera you should now start hearing the recorded audio for that camera. In my testing at this point I hear nothing, and ive waited 15 mins just to check if there is a delay between making the setting change and it taking affect. I then restart the recording server service responsible for said camera, and then once it has started I hear the audio.
Same thing in reverse. The microphone is set to record, I hear it in the recorded footage, i set the microphone to not record, but footage is still recorded with the microphone audio indefinitely until i restart the recoding server service.
Any ideas?

**Comment by joshooaj** [comment] 2022-05-13 17:03
My first thought was that if it's setup like it is by default, where on the "Client" tab of the camera in Management Client, you have the microphone set as a related device, so that when motion is detected, recording is done on the camera and "related devices", it could be that the motion is constant, so the recording of audio isn't getting triggered until the _next_ motion started event. Forcing a service restart would forcefully trigger a new motion started event in an environment with non-stop motion. 

In my test, my mic started recording immediately, even with the motion sensitivity setup so that the motion was constant. I did have to reload my Smart Client for it to discover the availability of the microphone since Smart Client only sees enabled devices on login, but when I visited playback, I could hear audio starting from the time I enabled it in Management Client. I also saw the recording status symbol on the mic immediately in Management Client so it seems to have worked as expected for me, using 2022 R1 with our test driver, StableFPS.

If you're toggling the checkbox on the "Record" tab of the microphone properties as in the screenshot below, I haven't had to restart the recording server service, but I have had to reload the Smart Client configuration when enabling recording in order to hear it in playback. But the recording begins immediately after saving the configuration.

0. Prior to enabling recording, the microphone is enabled, and the status symbol indicates the mic is live. I can hear audio in live tab of Smart Client.
1. Enable recording by checking the box and clicking save in Management Client.
2. Immediately, the "recording" status indicator appears on the microphone in Management Client.
3. In Smart Client, I can still hear audio in live, but it's not available in playback.
4. I press CTRL+R which I've mapped as a keyboard shortcut in Smart Client to "Reload server configuration". Logging out and in again would do the same thing.
5. After reloading configuration, I hear the mic in playback, and the audio begins at the same time as recording was enabled.

![image](https://user-images.githubusercontent.com/7669972/168321458-872d27ae-cddd-4360-bd8b-988b93198d10.png)

Again, I'm using our StableFPS driver to simulate a camera/mic feed and it's _possible_ that the device/driver could make a difference here, but it seems unlikely. Unfortunately I don't have a Hikvision camera to test with. I might have some time today for a call/remote session if you're available? Maybe we sort it out, or maybe we get enough information for you to get a tech support case started with our support team based on the behavior when changing the setting in Management Client?

**Comment by rdo-mgowland** [comment] 2022-05-16 08:50
Thanks heaps for looking into this for me. I'm in the process of getting budget approval to move to premium care so we can work direct with milestone on issues like this, but I'd be very appreciative if you wanted to do a remote support session. I just added another 32 samsung cameras to our system today, and even though their web interface shows their multiple stream settings as h265 or h264 with resolutions like 2500x1400, in the management client it shows all streams as MJEPG and only 1280x720, yet the live feeds in milestone are showing their 2500x1400 resolution but still MJPEG. I used the powershell toolkit to set them all to H264, and this is reflected in the management client, but the client software still shows them as jpeg codec, even after restarting the recording service. This powershell module is awesome and will be incredibly useful to us once our system works as expected :)
Something else to note, we use an AD service account to run all milestone services across our servers, not sure if that is having an impact. Ive tried looking through the various logs to see if I can see the management server trying to send new settings to the recording server and looking for errors, but i havnt come up with anything - though my knowledge on how the product works and communicates is obviously very weak, so I can only go so far with the troubleshooting. Ive also checked and confirmed there is no traffic getting blocked by our internal firewalls. 
Anyway really looking forward to making use of the tool, im very happy it exists!

**Comment by rdo-mgowland** [comment] 2022-05-16 08:51
What time zone are you in, Josh?

**Comment by joshooaj** [comment] 2022-06-30 21:53
Hey sorry I've been MIA on this repo for a while - I'm in Pacific Time (Oregon, USA).

I don't think the service accounts are going to be associated with this issue. More than likely if the cameras are setup to stream H264 but Smart Client still says it's JPEG, then you need to enter Setup mode in Smart Client and edit the properties for the cameras in the view. The image quality property should be "Full" - if it's _anything else_ then the recording server is going to transcode the video down to a pretty awful JPEG, probably increasing bandwidth between Smart Client and Recording Server, and increasing CPU load on the recording server.

**Closed** 2022-11-30 06:32 UTC
Labels: question
