### ISSUE TITLE
Error in PSTool exporting Avigilon with codec H.265 to .mkv format

### ISSUE THREAD

**Issue by MontseMunozFaus** [MilestoneSystemsInc/PowerShellSamples#121] opened 2024-02-15 09:07 UTC
Hello, we encountered an issue exporting video with PSTool from Avigilon with codec H.265 to .mkv format.

If we use code H.264, it works fine.
If we export with Smart Client using H.265, it also works fine.

It only fails when exporting with PSTool using H.265.

XProtect Corporate version 2023 R2
PSTool version 23.2.1

Enclosed:
* screenshot with device and camera settings.
* file ffmpeg-result obtained with command ffprobe

We have also a sample of video exported with Smart Client (14MB). Do you need it? We should send it privately (images of premises of end client can not be public).
Thank you

[ffmpeg-result.txt](https://github.com/MilestoneSystemsInc/PowerShellSamples/files/14293883/ffmpeg-result.txt)
![03 Device information](https://github.com/MilestoneSystemsInc/PowerShellSamples/assets/129446888/776d3327-83a1-4eb6-b315-5e5be218cd3e)
![04 Camera settings](https://github.com/MilestoneSystemsInc/PowerShellSamples/assets/129446888/b0dbcef6-27f0-497b-a4cd-517b46d7c8f6)

**Comment by MontseMunozFaus** [comment] 2024-02-16 08:19
Our Start-Export command is:
Start-Export -CameraIds $camera.Id  -StartTime $startDate -EndTime $endDate -Path "$exportFolderPath\$cameraName" -Name $exportFileName -Format mkv

All parameters introduced should be fine since with H.264 it is exporting videos

The error message we are getting is:
Start-Export : No video or audio in selected time period
At E:\New Script Development\Script2.0.ps1:59 char:13
+             Start-Export -CameraIds $camera.Id  -StartTime $startDate ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (VideoOS.Platform.Data.MKVExporter:MKVExporter) [Start-Export], NoVideoInTimeSpanMIPException
    + FullyQualifiedErrorId : VideoOS.Platform.NoVideoInTimeSpanMIPException: No video or audio in selected time period
   at VideoOS.Platform.SDK.Export.MKVExporter.StartExport(DateTime start, DateTime end)
   at VideoOS.Platform.Data.MKVExporter.StartExport(DateTime start, DateTime end)
       at MilestonePSTools.ExportCommands.StartExport.Export(IExporter exporter) in D:\a\MilestonePSTools\MilestonePSTools\src\MilestonePSTools\ExportCommands\StartExpo 
   rt.cs:line 260,MilestonePSTools.ExportCommands.StartExport

**Comment by joshooaj** [comment] 2024-02-16 17:47
I haven't been able to reproduce an export failure on my test system yet, even when using the sample MKV you provided as a video source.

Can you check to see if you also get an error when exporting to MKV using the sample export tool from our MIP SDK samples repository? You can download the ExportSample tool from the link below. Make sure to open the properties of the downloaded ZIP file and "unblock" the file before extracting it, then extract it and run ExportSample.exe.

https://milestonesys365-my.sharepoint.com/:u:/g/personal/jh_milestone_dk/Eb3wTf_v2QZAoCEHdEQ-iwABCcPkDvpbrrWUBIsLwetR8Q?e=xAlbJE

This is compiled from the MIP SDK developer sample at https://github.com/milestonesys/mipsdk-samples-component/tree/main/ExportSample and if this also fails, it will demonstrate that the issue is with the MIP SDK rather than with MilestonePSTools and the issue can be assigned to the appropriate team to resolve it.

If the ExportSample succeeds in exporting the H.265 video, then it would be a good idea to install and try again with MilestonePSTools 23.3.1 which uses the same version of MIP SDK as the sample above.

**Comment by MontseMunozFaus** [comment] 2024-02-23 22:20
Hi @joshooaj 
We tried you ExportSample and it worked, after changing the module version from 23.2.1 to 23.3.1 now it works and it's exporting the videos with codec H.265. Thanks for everything.

**Closed** 2024-02-25 19:34 UTC
Labels: bug, good first issue
