### ISSUE TITLE
Get-VmsRole: ClientProfile is always null

### ISSUE THREAD

**Issue by Silex** [MilestoneSystemsInc/PowerShellSamples#83] opened 2023-02-14 16:11 UTC
Hello,

1. In `Get-VmsRole`, the `ClientProfile` property is always null. I tried to find this using `Get-ConfigurationItem -Path /RoleFolder -ChildItems -Recurse` but there too I couldn't find the Smart Client profile. I need this to export my profiles & roles to a CSV file and import them back.
2. I have no clue how to get/set the "View Groups" tab permissions of a role. When looking at `$ms.ViewGroupFolder.ViewGroups[0]` I see that there's an obscure `ChangeSecurityPermissions` method but it accepts a user path?!
3. The example at https://www.milestonepstools.com/functions/get-configurationitem/#examples (and also for `Set-ConfigurationItem`) is broken (it sets the variable `$name` instead of the Name property), it'd be something like the example of `Set-ConfigurationItemProperty` instead.

Thanks :-)

**Comment by Silex** [comment] 2023-03-09 10:54
@joshooaj ping :-)

**Comment by Silex** [comment] 2023-03-15 08:07
Ok, for `2.` I self answered myself with this example from the MIPSDK:

``` c#
var changeSecurityPermissionsTask = camera.ChangeSecurityPermissions(role.Path); // TODO: should this be user[SID] instead?
changeSecurityPermissionsTask.SetProperty("GENERIC_READ", true.ToString());
changeSecurityPermissionsTask.SetProperty("VIEW_LIVE", true.ToString());
changeSecurityPermissionsTask.SetProperty("PLAYBACK", true.ToString());
changeSecurityPermissionsTask.ExecuteDefault();
```

Awfully named parameter `userPath` if you ask me.

**Comment by joshooaj** [comment] 2023-04-01 01:14
1. Yeah this is an SDK issue that I reported some months ago. I don't recall where it landed but I do believe "$role | Get-ConfigurationItem | Select-Object -ExpandProperty Properties" should show a "path" value for client profile, default time profile, and playback time profile.

2. I agree userPath sucks as a parameter name. It makes sense when you spend all your time in the MIP SDK and messing with configuration api "paths" but it's not a user friendly method parameter name. And the SDK docs often don't go into enough depth to be helpful. I can help with the powershell module but the best I can do with the MIP SDK classes and docs is make suggestions for improvement and I'm happy to pass your feedback along :)

3. I'll take a look at this next week. The intended behavior for Set-ConfigurationItem is that you modify the original item yourself, and then pipe it into Set-ConfigurationItem to effectively just save the changes by pushing them to the management server. The Set-ConfigurationItemProperty cmdlet makes it easier to set the value of a property in the local copy of that item before you push those changes to the management server with Set-ConfigurationItem.

**Closed** 2023-05-08 14:08 UTC
